version: 2

sources:
  - name: ga4_dbt # source name 
    description: 'Shopkasatria.vn GA4 Collected Data'
    database: shopkasatriavn # prj name
    schema: analytics_270502330 # dataset name
    tables:
      - name: dbt_demo #table name
        description: 'Test data, single day'
  - name: ga4_dbt_staging
    database: shopkasatriavn
    schema: staging
    tables:
      - name: dbt_audit
        freshness: 
          warn_after: { count: 24, period: hour }
          error_after: { count: 2, period: day}
          #filter sql
        loaded_at_field: created_at #must be in UTC format