version: 2

sources:
  - name: bigquery_ga4_shopkasatria # source name
    description: 'Shopkasatria.vn GA4 Collected Data'
    database: shopkasatriavn # prj name
    schema: analytics_270502330 # dataset name
    tables:
      - name: test
        description: 'Test data'